language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.9"
  - "5.12"
  - "6.14"
  - "7.10"
  - "8.11"
  - "9.11"
  - "10.9"
sudo: false
dist: trusty
env:
  global:
    # Suppress Node.js 0.6 compile warnings
    - "CXXCOM='$CXX -o $TARGET -c $CXXFLAGS $CCFLAGS -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-narrowing -Wno-strict-overflow $_CCCOMCOM $SOURCES'"
cache:
  directories:
    - node_modules
before_install:
  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"

  # Remove all non-test dependencies
  - "npm rm --save-dev benchmark"
  - "npm rm --save-dev beautify-benchmark"

  # Setup Node.js version-specific dependencies
  - "test $TRAVIS_NODE_VERSION != '0.6' || npm rm --save-dev istanbul"
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm rm --save-dev istanbul"
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 4 || npm rm --save-dev eslint eslint-plugin-markdown"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  # Run test script, depending on istanbul install
  - "test ! -z $(npm -ps ls istanbul) || npm test"
  - "test   -z $(npm -ps ls istanbul) || npm run-script test-ci"
  - "test   -z $(npm -ps ls eslint) || npm run-script lint"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
